server:
  port: 8080

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 765803471088-mir5i8v8g1lbfmu5murat0nqeopps338.apps.googleusercontent.com
#            client-secret: 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
#            scope: openid,profile,email
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs/